# app\domain\application_statuses.py

from __future__ import annotations

APPLICATION_STATUS_DRAFT = "draft"
APPLICATION_STATUS_SUBMITTED = "submitted"
APPLICATION_STATUS_INTERVIEW = "interview"
APPLICATION_STATUS_REJECTED = "rejected"
APPLICATION_STATUS_OFFER = "offer"

APPLICATION_STATUSES: set[str] = {
    APPLICATION_STATUS_DRAFT,
    APPLICATION_STATUS_SUBMITTED,
    APPLICATION_STATUS_INTERVIEW,
    APPLICATION_STATUS_REJECTED,
    APPLICATION_STATUS_OFFER,
}

ALLOWED_STATUS_TRANSITIONS: dict[str, set[str]] = {
    APPLICATION_STATUS_DRAFT: {
        APPLICATION_STATUS_SUBMITTED,
    },
    APPLICATION_STATUS_SUBMITTED: {
        APPLICATION_STATUS_INTERVIEW,
        APPLICATION_STATUS_REJECTED,
        APPLICATION_STATUS_OFFER,
    },
    APPLICATION_STATUS_INTERVIEW: {
        APPLICATION_STATUS_REJECTED,
        APPLICATION_STATUS_OFFER,
    },
    APPLICATION_STATUS_REJECTED: set(),
    APPLICATION_STATUS_OFFER: set(),
}