# backend\alembic\script.py.mako

"""add_tokens_used_json_to_ai_runs

Revision ID: 1458eac2b109
Revises: 559468b67048
Create Date: 2026-05-06 11:02:40.850649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '1458eac2b109'
down_revision: Union[str, Sequence[str], None] = '559468b67048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_runs', sa.Column('tokens_used_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_runs', 'tokens_used_json')
    # ### end Alembic commands ###