# backend\alembic\script.py.mako

"""add impact_measurements table

Revision ID: 32d269e976bb
Revises: c7a358fd3228
Create Date: 2026-05-12 15:20:21.333840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '32d269e976bb'
down_revision: Union[str, Sequence[str], None] = 'c7a358fd3228'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impact_measurements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recommendation_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('before_snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('after_snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('delta_overall', sa.Float(), nullable=False),
    sa.Column('delta_components', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['after_snapshot_id'], ['evaluation_snapshots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['before_snapshot_id'], ['evaluation_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Add indexes
    op.create_index(op.f('ix_impact_measurements_recommendation_id'), 'impact_measurements', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_impact_measurements_document_id'), 'impact_measurements', ['document_id'], unique=False)
    op.create_index(op.f('ix_impact_measurements_created_at'), 'impact_measurements', ['created_at'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_impact_measurements_created_at'), table_name='impact_measurements')
    op.drop_index(op.f('ix_impact_measurements_document_id'), table_name='impact_measurements')
    op.drop_index(op.f('ix_impact_measurements_recommendation_id'), table_name='impact_measurements')
    op.drop_table('impact_measurements')
    # ### end Alembic commands ###