# backend\alembic\script.py.mako

"""Add interview_answer_attempts table

Revision ID: 559468b67048
Revises: b8e0b417ae85
Create Date: 2026-05-05 15:08:52.916174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '559468b67048'
down_revision: Union[str, Sequence[str], None] = 'b8e0b417ae85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_answer_attempts',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.String(length=100), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('feedback_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_answer_attempts_question_id'), 'interview_answer_attempts', ['question_id'], unique=False)
    op.create_index(op.f('ix_interview_answer_attempts_session_id'), 'interview_answer_attempts', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_answer_attempts_session_id'), table_name='interview_answer_attempts')
    op.drop_index(op.f('ix_interview_answer_attempts_question_id'), table_name='interview_answer_attempts')
    op.drop_table('interview_answer_attempts')
    # ### end Alembic commands ###