# backend\alembic\script.py.mako

"""add_pipeline_execution_tables

Revision ID: 8a2b36d82e8a
Revises: g2b3c4d5e6f7
Create Date: 2026-05-11 20:53:46.482519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '8a2b36d82e8a'
down_revision: Union[str, Sequence[str], None] = 'g2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_executions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('vacancy_id', sa.Uuid(), nullable=True),
    sa.Column('profile_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('pipeline_version', sa.String(length=50), nullable=True),
    sa.Column('calibration_version', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resume_document_id', sa.Uuid(), nullable=True),
    sa.Column('evaluation_snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('review_id', sa.Uuid(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('artifacts_json', sa.JSON(), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_snapshot_id'], ['vacancy_analyses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resume_document_id'], ['document_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['review_id'], ['document_reviews.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pipeline_executions_profile_status', 'pipeline_executions', ['profile_id', 'status'], unique=False)
    op.create_index('idx_pipeline_executions_user_status', 'pipeline_executions', ['user_id', 'status'], unique=False)
    op.create_index('idx_pipeline_executions_vacancy_status', 'pipeline_executions', ['vacancy_id', 'status'], unique=False)
    op.create_index(op.f('ix_pipeline_executions_profile_id'), 'pipeline_executions', ['profile_id'], unique=False)
    op.create_index(op.f('ix_pipeline_executions_status'), 'pipeline_executions', ['status'], unique=False)
    op.create_index(op.f('ix_pipeline_executions_user_id'), 'pipeline_executions', ['user_id'], unique=False)
    op.create_index(op.f('ix_pipeline_executions_vacancy_id'), 'pipeline_executions', ['vacancy_id'], unique=False)
    op.create_table('pipeline_execution_steps',
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('step_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('input_artifact_ids', sa.JSON(), nullable=False),
    sa.Column('output_artifact_ids', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['pipeline_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pipeline_execution_steps_execution_name', 'pipeline_execution_steps', ['execution_id', 'step_name'], unique=False)
    op.create_index(op.f('ix_pipeline_execution_steps_execution_id'), 'pipeline_execution_steps', ['execution_id'], unique=False)
    op.create_index(op.f('ix_pipeline_execution_steps_status'), 'pipeline_execution_steps', ['status'], unique=False)
    op.create_index(op.f('ix_pipeline_execution_steps_step_name'), 'pipeline_execution_steps', ['step_name'], unique=False)
    op.create_table('pipeline_events',
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('step_id', sa.Uuid(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['pipeline_executions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['pipeline_execution_steps.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pipeline_events_execution_type', 'pipeline_events', ['execution_id', 'event_type'], unique=False)
    op.create_index('idx_pipeline_events_type_severity', 'pipeline_events', ['event_type', 'severity'], unique=False)
    op.create_index(op.f('ix_pipeline_events_event_type'), 'pipeline_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_pipeline_events_execution_id'), 'pipeline_events', ['execution_id'], unique=False)
    op.create_index(op.f('ix_pipeline_events_severity'), 'pipeline_events', ['severity'], unique=False)
    op.create_index(op.f('ix_pipeline_events_step_id'), 'pipeline_events', ['step_id'], unique=False)
    op.drop_index('ix_application_events_application_type', table_name='application_events')
    op.create_index('idx_application_events_application_type', 'application_events', ['application_id', 'event_type'], unique=False)
    op.drop_index('ix_document_reviews_document_user', table_name='document_reviews')
    op.create_index('idx_document_reviews_document_user', 'document_reviews', ['document_id', 'user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_document_reviews_document_user', table_name='document_reviews')
    op.create_index('ix_document_reviews_document_user', 'document_reviews', ['document_id', 'user_id'], unique=False)
    op.drop_index('idx_application_events_application_type', table_name='application_events')
    op.create_index('ix_application_events_application_type', 'application_events', ['application_id', 'event_type'], unique=False)
    op.drop_index(op.f('ix_pipeline_events_step_id'), table_name='pipeline_events')
    op.drop_index(op.f('ix_pipeline_events_severity'), table_name='pipeline_events')
    op.drop_index(op.f('ix_pipeline_events_execution_id'), table_name='pipeline_events')
    op.drop_index(op.f('ix_pipeline_events_event_type'), table_name='pipeline_events')
    op.drop_index('idx_pipeline_events_type_severity', table_name='pipeline_events')
    op.drop_index('idx_pipeline_events_execution_type', table_name='pipeline_events')
    op.drop_table('pipeline_events')
    op.drop_index(op.f('ix_pipeline_execution_steps_step_name'), table_name='pipeline_execution_steps')
    op.drop_index(op.f('ix_pipeline_execution_steps_status'), table_name='pipeline_execution_steps')
    op.drop_index(op.f('ix_pipeline_execution_steps_execution_id'), table_name='pipeline_execution_steps')
    op.drop_index('idx_pipeline_execution_steps_execution_name', table_name='pipeline_execution_steps')
    op.drop_table('pipeline_execution_steps')
    op.drop_index(op.f('ix_pipeline_executions_vacancy_id'), table_name='pipeline_executions')
    op.drop_index(op.f('ix_pipeline_executions_user_id'), table_name='pipeline_executions')
    op.drop_index(op.f('ix_pipeline_executions_status'), table_name='pipeline_executions')
    op.drop_index(op.f('ix_pipeline_executions_profile_id'), table_name='pipeline_executions')
    op.drop_index('idx_pipeline_executions_vacancy_status', table_name='pipeline_executions')
    op.drop_index('idx_pipeline_executions_user_status', table_name='pipeline_executions')
    op.drop_index('idx_pipeline_executions_profile_status', table_name='pipeline_executions')
    op.drop_table('pipeline_executions')
    # ### end Alembic commands ###