# backend\alembic\script.py.mako

"""initial_schema

Revision ID: 9de02e41efad
Revises: 
Create Date: 2026-04-13 21:10:21.575422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '9de02e41efad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('auth_provider', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ai_runs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_name', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('input_snapshot_json', sa.JSON(), nullable=False),
    sa.Column('output_snapshot_json', sa.JSON(), nullable=False),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_runs_target_id'), 'ai_runs', ['target_id'], unique=False)
    op.create_index(op.f('ix_ai_runs_user_id'), 'ai_runs', ['user_id'], unique=False)
    op.create_index(op.f('ix_ai_runs_workflow_name'), 'ai_runs', ['workflow_name'], unique=False)
    op.create_table('candidate_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('headline', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('target_roles_json', sa.JSON(), nullable=False),
    sa.Column('work_format_preferences_json', sa.JSON(), nullable=False),
    sa.Column('salary_expectation', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_currency', sa.String(length=10), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_profiles_user_id'), 'candidate_profiles', ['user_id'], unique=True)
    op.create_table('source_files',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('file_kind', sa.String(length=50), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_source_files_file_kind'), 'source_files', ['file_kind'], unique=False)
    op.create_index(op.f('ix_source_files_user_id'), 'source_files', ['user_id'], unique=False)
    op.create_table('vacancies',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('salary_from', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_to', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_currency', sa.String(length=10), nullable=True),
    sa.Column('description_raw', sa.Text(), nullable=False),
    sa.Column('normalized_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacancies_external_id'), 'vacancies', ['external_id'], unique=False)
    op.create_index(op.f('ix_vacancies_user_id'), 'vacancies', ['user_id'], unique=False)
    op.create_table('candidate_experiences',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description_raw', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_experiences_profile_id'), 'candidate_experiences', ['profile_id'], unique=False)
    op.create_table('document_versions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('vacancy_id', sa.Uuid(), nullable=True),
    sa.Column('derived_from_id', sa.Uuid(), nullable=True),
    sa.Column('document_kind', sa.String(length=50), nullable=False),
    sa.Column('version_label', sa.String(length=100), nullable=True),
    sa.Column('review_status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('rendered_text', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['derived_from_id'], ['document_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_versions_derived_from_id'), 'document_versions', ['derived_from_id'], unique=False)
    op.create_index(op.f('ix_document_versions_document_kind'), 'document_versions', ['document_kind'], unique=False)
    op.create_index(op.f('ix_document_versions_user_id'), 'document_versions', ['user_id'], unique=False)
    op.create_index(op.f('ix_document_versions_vacancy_id'), 'document_versions', ['vacancy_id'], unique=False)
    op.create_table('interview_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('vacancy_id', sa.Uuid(), nullable=True),
    sa.Column('session_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('question_set_json', sa.JSON(), nullable=False),
    sa.Column('answers_json', sa.JSON(), nullable=False),
    sa.Column('feedback_json', sa.JSON(), nullable=False),
    sa.Column('score_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_sessions_user_id'), 'interview_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_interview_sessions_vacancy_id'), 'interview_sessions', ['vacancy_id'], unique=False)
    op.create_table('vacancy_analyses',
    sa.Column('vacancy_id', sa.Uuid(), nullable=False),
    sa.Column('must_have_json', sa.JSON(), nullable=False),
    sa.Column('nice_to_have_json', sa.JSON(), nullable=False),
    sa.Column('keywords_json', sa.JSON(), nullable=False),
    sa.Column('gaps_json', sa.JSON(), nullable=False),
    sa.Column('strengths_json', sa.JSON(), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('analysis_version', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacancy_analyses_vacancy_id'), 'vacancy_analyses', ['vacancy_id'], unique=False)
    op.create_table('application_records',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('vacancy_id', sa.Uuid(), nullable=False),
    sa.Column('resume_document_id', sa.Uuid(), nullable=True),
    sa.Column('cover_letter_document_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cover_letter_document_id'], ['document_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resume_document_id'], ['document_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_records_cover_letter_document_id'), 'application_records', ['cover_letter_document_id'], unique=False)
    op.create_index(op.f('ix_application_records_resume_document_id'), 'application_records', ['resume_document_id'], unique=False)
    op.create_index(op.f('ix_application_records_user_id'), 'application_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_application_records_vacancy_id'), 'application_records', ['vacancy_id'], unique=False)
    op.create_table('candidate_achievements',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('experience_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('situation', sa.Text(), nullable=True),
    sa.Column('task', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('metric_text', sa.String(length=255), nullable=True),
    sa.Column('evidence_note', sa.Text(), nullable=True),
    sa.Column('fact_status', sa.String(length=30), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['candidate_experiences.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_achievements_experience_id'), 'candidate_achievements', ['experience_id'], unique=False)
    op.create_index(op.f('ix_candidate_achievements_profile_id'), 'candidate_achievements', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_achievements_profile_id'), table_name='candidate_achievements')
    op.drop_index(op.f('ix_candidate_achievements_experience_id'), table_name='candidate_achievements')
    op.drop_table('candidate_achievements')
    op.drop_index(op.f('ix_application_records_vacancy_id'), table_name='application_records')
    op.drop_index(op.f('ix_application_records_user_id'), table_name='application_records')
    op.drop_index(op.f('ix_application_records_resume_document_id'), table_name='application_records')
    op.drop_index(op.f('ix_application_records_cover_letter_document_id'), table_name='application_records')
    op.drop_table('application_records')
    op.drop_index(op.f('ix_vacancy_analyses_vacancy_id'), table_name='vacancy_analyses')
    op.drop_table('vacancy_analyses')
    op.drop_index(op.f('ix_interview_sessions_vacancy_id'), table_name='interview_sessions')
    op.drop_index(op.f('ix_interview_sessions_user_id'), table_name='interview_sessions')
    op.drop_table('interview_sessions')
    op.drop_index(op.f('ix_document_versions_vacancy_id'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_user_id'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_document_kind'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_derived_from_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_candidate_experiences_profile_id'), table_name='candidate_experiences')
    op.drop_table('candidate_experiences')
    op.drop_index(op.f('ix_vacancies_user_id'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_external_id'), table_name='vacancies')
    op.drop_table('vacancies')
    op.drop_index(op.f('ix_source_files_user_id'), table_name='source_files')
    op.drop_index(op.f('ix_source_files_file_kind'), table_name='source_files')
    op.drop_table('source_files')
    op.drop_index(op.f('ix_candidate_profiles_user_id'), table_name='candidate_profiles')
    op.drop_table('candidate_profiles')
    op.drop_index(op.f('ix_ai_runs_workflow_name'), table_name='ai_runs')
    op.drop_index(op.f('ix_ai_runs_user_id'), table_name='ai_runs')
    op.drop_index(op.f('ix_ai_runs_target_id'), table_name='ai_runs')
    op.drop_table('ai_runs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###