"""add previous_snapshot_id to evaluation_snapshots

Revision ID: a1b2c3d4e5f8
Revises: c7a358fd3228
Create Date: 2026-05-12 14:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f8'
down_revision: Union[str, Sequence[str], None] = 'c7a358fd3228'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluation_snapshots', sa.Column(
        'previous_snapshot_id',
        sa.Uuid(),
        sa.ForeignKey('evaluation_snapshots.id'),
        nullable=True,
    ))
    
    # Create index for efficient chain traversal
    op.create_index('idx_evaluation_snapshots_previous', 'evaluation_snapshots', ['previous_snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_evaluation_snapshots_previous', table_name='evaluation_snapshots')
    op.drop_column('evaluation_snapshots', 'previous_snapshot_id')
    # ### end Alembic commands ###
