"""add pipeline_executions table

Revision ID: b1c2d3e4f5g6
Revises: a1b2c3d4e5f8
Create Date: 2026-05-12 15:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1c2d3e4f5g6'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())
    if 'pipeline_executions' in existing_tables:
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_executions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('execution_type', sa.String(length=50), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('failure_code', sa.String(length=100), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('output_artifact_ids', sa.JSON(), nullable=False),
    sa.Column('input_params', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pipeline_executions_user_created', 'pipeline_executions', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_pipeline_executions_status_created', 'pipeline_executions', ['status', 'created_at'], unique=False)
    op.create_index('idx_pipeline_executions_type_status', 'pipeline_executions', ['execution_type', 'status'], unique=False)
    op.create_index('ix_pipeline_executions_document_id', 'pipeline_executions', ['document_id'], unique=False)
    op.create_index('ix_pipeline_executions_failure_code', 'pipeline_executions', ['failure_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())
    if 'pipeline_executions' not in existing_tables:
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pipeline_executions_failure_code', table_name='pipeline_executions')
    op.drop_index('idx_pipeline_executions_type_status', table_name='pipeline_executions')
    op.drop_index('idx_pipeline_executions_status_created', table_name='pipeline_executions')
    op.drop_index('idx_pipeline_executions_user_created', table_name='pipeline_executions')
    op.drop_index('ix_pipeline_executions_document_id', table_name='pipeline_executions')
    op.drop_table('pipeline_executions')
    # ### end Alembic commands ###
