# backend\alembic\script.py.mako

"""add_provider_name_to_ai_runs

Revision ID: b8e0b417ae85
Revises: badc1805f0ba
Create Date: 2026-05-04 14:28:10.403506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'b8e0b417ae85'
down_revision: Union[str, Sequence[str], None] = 'badc1805f0ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_runs', sa.Column('provider_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_runs', 'provider_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_sessions_token_hash'), table_name='refresh_sessions')
    op.create_index(op.f('ix_refresh_sessions_token_hash'), 'refresh_sessions', ['token_hash'], unique=False)
    op.create_unique_constraint(op.f('refresh_sessions_token_hash_key'), 'refresh_sessions', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_refresh_sessions_expires_at'), 'refresh_sessions', ['expires_at'], unique=False)
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=False)
    op.create_unique_constraint(op.f('password_reset_tokens_token_hash_key'), 'password_reset_tokens', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_password_reset_tokens_used_at'), 'password_reset_tokens', ['used_at'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_expires_at'), 'password_reset_tokens', ['expires_at'], unique=False)
    op.drop_column('ai_runs', 'provider_name')
    # ### end Alembic commands ###