# backend\alembic\script.py.mako

"""add_file_extractions

Revision ID: c5e1b2062553
Revises: 9de02e41efad
Create Date: 2026-04-14 08:43:26.973722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'c5e1b2062553'
down_revision: Union[str, Sequence[str], None] = '9de02e41efad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_extractions',
    sa.Column('source_file_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('parser_name', sa.String(length=100), nullable=False),
    sa.Column('parser_version', sa.String(length=50), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('extracted_metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_extractions_source_file_id'), 'file_extractions', ['source_file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_extractions_source_file_id'), table_name='file_extractions')
    op.drop_table('file_extractions')
    # ### end Alembic commands ###